name: social
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6   # For iOS-style icons
  flutter_launcher_icons: ^0.11.0
  firebase_core: ^2.14.0    
  firebase_auth: ^4.20.0     
  cloud_firestore: ^4.7.3   
  provider: ^6.1.2
  flutter_slidable: ^3.1.1
  awesome_notifications: ^0.9.3+1
  firebase_messaging: ^14.9.4
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0     # For linting and code style enforcement

flutter:
  uses-material-design: true

  assets:
    - assets/images/social.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/social.png"
